### ISSUE TITLE
Can we move Verification code button to diffrent spot on Verify email page

### ISSUE THREAD

**Issue by rahulvageriya** [brightlayer-ui/react-native-workflows#157]
@joebochill  just an suggestion , can we move verification code button to different spot as when we type verification code,  keyboard gets enable due to that next button looks hidden . then we press reset verification email button . 

![Simulator Screen Shot - iPhone 13 - 2022-06-17 at 15 59 50](https://user-images.githubusercontent.com/99805091/174281551-488ba804-ce33-4aff-acbe-480df02ac7cb.png)

**Comment by joebochill** [comment]
This is a complaint we have heard before, and I agree. We can look into redesigning the resend button so it doesn't look so much like the primary action.

**Comment by daileytj** [comment]
@huayunh Do you have any recommendations for design on this one?

**Comment by huayunh** [comment]
Can do ^

> Didn't receive a code? <ins>**Resend**</ins>

**Comment by daileytj** [comment]
![Simulator Screen Shot - iPhone 12 - 2022-07-01 at 14 31 53](https://user-images.githubusercontent.com/13989985/176952139-0b147f0e-6120-4c3a-94c1-5ba3027eb0e6.png)
![Screen Shot 2022-07-01 at 2 32 10 PM (2)](https://user-images.githubusercontent.com/13989985/176952141-e4013a3b-cbcd-4230-9518-b6ad076d7b81.png)
@huayunh @joebochill thoughts? Should I add some padding to the text button so that on click theres some separation? I'm just concerned that the gap will be too large when the active state isn't shown. We could shrink the horizontal margin on the button if we want to do that. The margin-top is off a bit from standard as well since I'm center aligning items to the button. I can adjust this by dropping the margin-top relative to the button padding-top if we want to.
